# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'SimpleWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SimpleWeatherApp
  pod 'Alamofire', '~> 5.1'
  pod 'SwiftLint'

  target 'SimpleWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SimpleWeatherAppUITests' do
    # Pods for testing
  end

end
